name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync_bibliography:
    strategy:
      matrix:
        include:
          - repo_owner: andstor
            repo_name: paper-template
          - repo_owner: andstor
            repo_name: security-patch-detection-agent
    runs-on: ubuntu-latest
    steps:
    - name: Copy bib file to ${{ matrix.repo_owner }}/${{ matrix.repo_name }}
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /bibliography.bib
        dst_path: /bibliography.bib
        dst_owner: ${{ matrix.repo_owner }}
        dst_repo_name: ${{ matrix.repo_name }}
        dst_branch: main
        src_branch: main
        username: nutsbot
        email: andr3.storhaug+bot@gmail.com

